---
# requires pysnowi
#
#
- name: include vars
  include_vars: "/terraform_demo/vars/snow_vars.yml"

- name: Find record
  snow_record:
    table: sc_request
    state: present
    username: "{{ snow_user }}"
    password: "{{ snow_pass }}"
    instance: "{{ snow_instance }}"
    number: "{{ snow_number }}"
  register: get_req
