---
  - win_domain_membership:
      dns_domain_name: lab.loc
      domain_admin_user: "{{ domain_user }}@{{ domain_name }}"
      domain_admin_password: "{{ domain_password }}"
      state: domain
      log_path: C:\Windows\Temp\ad_join_log.txt
    register: domain_state

  - win_reboot:
    when: domain_state.reboot_required
