---
- name: Install LogInsight Agent
  hosts: all
  gather_facts: yes
  vars:
    base_url: http://10.3.50.48/
    wininstaller: VMware-Log-Insight-Agent-8.0.0-14743436_10.3.98.66.msi
    winproduct_id:  {69CFC17D-9E9D-4262-AFA1-BCB517D14D18}
    lininstaller: VMware-Log-Insight-Agent-8.0.0-14743436.noarch_10.3.98.66.rpm


  tasks:
  
  - name: Install the windows agent MSI
    win_package:
      path: "{{ base_url }}/{{ wininstaller }}"
      product_id: "{{ winproduct_id }}"
      state: present
    when: ansible_facts['os_family'] == 'Windows'

  - name: Install the linux agent RPM
    yum:
      name: "{{ base_url }}/{{ lininstaller }}"
      state: present
    when: ansible_facts['os_family'] == 'RedHat'
    notify: Enable Redhat LI Agent

  handlers:
   
  - name: Enable Redhat LI Agent
    service:
      name: liagentd.service
      state: started
      enabled: yes
